
-- Selecting all of the agent names, amounts and department names from the SALES_AGENTS JOIN
SELECT (SALES_AGENTS.AGENT_NAME, SALES_RECORDS.AMOUNTS, DEPARTMENTS.DEPARTMENT_NAME
FROM ((SALES_AGENTS
-- Using INNER JOIN to join tables on their Keys
INNER JOIN SALES_RECORDS ON SALES_AGENTS.AGENT_ID = SALES_RECORDS.AGENT_ID)
INNER JOIN DEPARTMENTS ON SALES_AGENTS.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID)
